### PR TITLE
feat(tests):add patch tests and cleanup flag

### PR DESCRIPTION
**Pull request by rgarg1**
This PR implements the following:

- Added tests to modify work items
- Added tests to delete a space
- Added a new flag _cleanup_, which user can use to specify auto-deletion of spaces after the tests run
- Updated documentation
- Updated test runner used to trigger API tests on CentOS, to delete spaces
- Removed stale and incomplete files for forge automation

### CODE REVIEW

**Comment by rgarg1** [comment]
@jarifibrahim Please review and let me know if any of these changes impact Planner EE tests

**Comment by jarifibrahim** [comment]
@rgarg1 Since the space deletion is failing due to https://github.com/openshiftio/openshift.io/issues/3503, shouldn't the tests also fail? The tests should fail until issue https://github.com/openshiftio/openshift.io/issues/3503 has been resolved.

**Comment by rgarg1** [comment]
I thought of asserting the space deletion, but intentionally kept it this way, or else the API tests will always fail on CentOS CI. Once the defect is fixed, I can change it to assert.

**Comment by rgarg1** [comment]
Can we merge this @jarifibrahim

**Pull request merged**
