### PR TITLE
Get rid of progress bars when yum installs

### PR DESCRIPTION
**Pull request by kwk**
See this https://github.com/SatelliteQE/automation-tools/issues/296 for an example of how the output changes when you use `-d1` on `yum install`.

### CODE REVIEW

**Comment by ppitonak** [comment]
Why?

**Comment by rgarg1** [comment]
@kwk This is the file being used for API tests:
https://github.com/fabric8io/fabric8-test/blob/master/EE_API_automation/pytest/src/Dockerfile

Although, this PR should also go in. I'll assign @ppitonak as a reviewer as he's maintaining EE tests.

**Comment by kwk** [comment]
> Why?

To silence the output in Jenkins a bit and have us focus on the results of the execution instead of progress bars that are rendered in ASCII ;)

**Comment by ppitonak** [comment]
@kwk I agree that it prints too much to Jenkins log but it helped us multiple times in the past, e.g. when Chrome Stable rpm disappeared from yum repositories. How often do you watch this log?

**Comment by kwk** [comment]
> @kwk I agree that it prints too much to Jenkins log but it helped us multiple times in the past, e.g. when Chrome Stable rpm disappeared from yum repositories. How often do you watch this log? I personally do it only when it breaks, last 30 builds are green.

I don't look at the logs too often which emphasizes the problem for me to find the right bits. If you require chrome stable and it isn't installed, then yum will fail and that should cause the build job to fail as well. I noticed that yum won't tell you that it couldn't find a package when `--quiet` is used. But let's change that to `-d1` to get rid of the progress bars at least. It will still tell you when it cannot install a package.

Here're the example:

**with --quiet**
```
$ yum install --quiet foo
$
```
Notice that it indeed does not show you anything.


**with -d1**
```
$ yum install -y -d1 foo
Last metadata expiration check: 2:55:43 ago on Wed Jul 18 11:21:44 2018.
No match for argument: foo
Error: Unable to find a match
$
```
Notice that it shows you that a package is missing.

**Comment by ppitonak** [comment]
> If you require chrome stable and it isn't installed, then yum will fail and that should cause the build job to fail as well.

Yes, this is exactly what I expected but that didn't happen ;) `-d1` doesn't produce desired output, `-d2` could be used.

```bash
# yum install -y -d1 rsync foo
Package rsync-3.1.2-4.el7.x86_64 already installed and latest version
```

```bash
# yum install -y -d2 rsync foo
Loaded plugins: fastestmirror, ovl
Loading mirror speeds from cached hostfile
 * base: ftp.sh.cvut.cz
 * extras: ftp.sh.cvut.cz
 * updates: ftp.sh.cvut.cz
Package rsync-3.1.2-4.el7.x86_64 already installed and latest version
No package foo available.
Nothing to do
```

**Comment by ppitonak** [comment]
@kwk IMHO no need to revert because original impl wasn't safe either.

**Pull request merged**
