### PR TITLE
names of scripts unified and simplified

### PR DESCRIPTION
**Pull request by ppitonak**
This is a preparation for new Jenkins jobs

* 'ts' part in CICO script removed
* 'EE' and 'ee' changed to 'e2e' to be unified with Jenkins jobs naming conventions
* new CICO script created so that old Jenkins jobs work without interruption

### CODE REVIEW

**Comment by ppitonak** [comment]
That's the reason why I created a script with old name that just calls the new script

**Comment by ldimaggi** [comment]
+1 - ok - LGTM!

**Comment by ppitonak** [comment]
I decided to create a completely new script (old jobs will still be using old script so *no interruptions* are expected). It will now work very similarly to `local_cico_run_e2e_tests.sh` - no parameters for script but source the environment variables - this will scale much better.

See https://github.com/ppitonak/openshiftio-cico-jobs/commit/b9415e46d7d7ab5c72518b4292f5e6ab43bb4881 for future related changes in CICO yaml - this PR is a prerequisite for new Jenkins jobs.

**Comment by ppitonak** [comment]
New cico yaml changes https://github.com/ppitonak/openshiftio-cico-jobs/tree/new_e2e_jobs and new code in this PR

**Pull request merged**
