### PR TITLE
Forge wizard: import repositories flow

### PR DESCRIPTION
**Pull request by corinnekrych**
Fixes https://github.com/fabric8io/fabric8-test/issues/114

### CODE REVIEW

**Comment by corinnekrych** [comment]
@rgarg1 Could you review? 
I had trouble for testing the last test, how do you get the first item on an array in [there](https://github.com/fabric8io/fabric8-test/pull/115/files#diff-b26ec0cd19ccfbae4ac540d9322e49efR239)?

**Comment by rgarg1** [comment]
I can't see 'data' in the response json as it contains only an array. Could you pls double check for missing data. The response from the API seems to not match the standard.

**Comment by corinnekrych** [comment]
@rgarg1 Indeed the Forge API is not JSON-API compliant. 
If this is a requirement the whole Forge API need to be revisited.
cc @jstrachan @aslakknutsen 

It's a REST API though and it does return a valid JSON (array is ok as per:  https://tools.ietf.org/html/rfc7159)
It seems pyresttest does not handle an array as result, I've tried several syntax, none work :(
Let's remove the check for step4 for the time being.

**Comment by corinnekrych** [comment]
@rgarg1 I've just logged https://github.com/fabric8io/fabric8-test/issues/130 and i will work on it once this one is merged.

**Comment by corinnekrych** [comment]
@rgarg1 ok to merge this one?

**Pull request merged**
