### PR TITLE
Update pyresttest setup instructions

### PR DESCRIPTION
**Pull request by jarifibrahim**
The command `pip install pyresttest` installs `pyresttest` and all the related dependencies.

### CODE REVIEW

**Comment by jarifibrahim** [comment]
@rgarg1 Please review.

**Comment by jarifibrahim** [comment]
@rgarg1 Yes. It takes care of installing all the dependencies of `Pyresttest`

**Comment by rgarg1** [comment]
I'd recommend you make the 3rd step as optional and leave it there, to be used only if a dependency is missed during pyresttest install.

**Comment by jarifibrahim** [comment]
@rgarg1 The 3rd step is useful only if the user is trying to install pyresttest manually(using the source code), that is by pulling the source code and then running the `setup.py` file within it.
When we do `pip install pyresttest`, `pip` installs all the dependencies for the `pyresttest` package and then it actually installs `pyresttest`.
Also, according to the [Pyresttest Docs](https://github.com/svanoort/pyresttest#installation) this is the easiest way of installation.

**Pull request merged**
