### PR TITLE
Add an Import an Application interaction.

### PR DESCRIPTION
**Pull request by pmacik**

### CODE REVIEW

**Comment by ljelinkova** [comment]
Do you plan to use space_dashboard_interactions.ts in the booster tests? If no, then it is not necessary to add importRepo() method there since we do not plan to import repository in smoketest at the moment. 

Other than that, it looks OK.

**Comment by pmacik** [comment]
> Do you plan to use space_dashboard_interactions.ts in the booster tests? If no, then it is not necessary to add importRepo() method there since we do not plan to import repository in smoketest at the moment.

@ljelinkova Yes, we do.

**Comment by ljelinkova** [comment]
In that case, what is the strategy: string parameter in importRepo? It might be better to create enum and pass it as an argument to the function.

**Comment by pmacik** [comment]
There is a related PR https://github.com/fabric8io/fabric8-test/pull/686 for passing the repo name.
If it is en empty string (by default) the space name is used instead (as with the tests for creating a QS).

**Comment by ljelinkova** [comment]
I do not know what  strategy: string parameter means in importRepo function. In general, we try to use enums instead of passing strings if the values can be enumerated, e.g.

https://github.com/fabric8io/fabric8-test/blob/master/ee_tests/src/support/feature_level.ts

**Comment by pmacik** [comment]
Ah, I understand... with the `importRepo` function I simply started with `createQuickstart` and done it similarly... I agree to use enums where possible - actualy there is a [`release_strategy`](https://github.com/fabric8io/fabric8-test/blob/master/ee_tests/src/support/release_strategy.ts) enum already in the code. But I suggest to do it in a different PR.

**Comment by ljelinkova** [comment]
Agreed. Please create new issue so that we won't forget about replacing strategy by enum.

**Comment by pmacik** [comment]
> Agreed. Please create new issue so that we won't forget about replacing strategy by enum.

Issue created: https://github.com/fabric8io/fabric8-test/issues/693

**Pull request merged**
